CREATE USER C##SCOTT IDENTIFIED BY tiger;
GRANT CONNECT TO C##SCOTT;
CREATE TABLESPACE SCOTT_DATA DATAFILE 'scott_data.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 10G;
CREATE TEMPORARY TABLESPACE SCOTT_TEMP TEMPFILE 'scott_temp.dbf' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 10G;
ALTER USER C##SCOTT DEFAULT TABLESPACE SCOTT_DATA TEMPORARY TABLESPACE SCOTT_TEMP;

CONNECT C##SCOTT/tiger;

-- Run all the other scripts
@create_tables.sql